name: My first workflow

on: push

jobs: 
  my-amazing-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The amazing job is complete"
      - run: echo "This was triggered by a ${{ github.ecent_name }} event."
      - run: echo "The amaxing job is complete"
  my-amazing-checkout-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cloning ${{ github.repository }} to the runner..."
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - run: echo "The reoo has been cloned and is ready for... well... anything!"
      - name: List files in repo
        run: |
          ls -lah ${{ github.workspace }};
          echo "Contents of index.html";
          cat index.html
      - run: echo "This job's status is ${{ job.status }}"
